### ISSUE TITLE
add `addFrame` and `downloadBundle` to `Recorder` class

### ISSUE THREAD

**Issue by hapticdata** [MathiasPaumgarten/canvas-recorder#10]
As you know, I typically control my sketches / apps with my own loop or library [animitter](https://github.com/hapticdata/animitter) and deciding to record the frames with `canvas-recorder` comes mid-project. 
Using `addFrame` and `downloadBundle` is excellent for this, recording the frames with the addition of just a couple lines; however those functions use a shared instance. If I have multiple canvases to simultaneously save they end up interleaved in the resulting bundle.

It would be very helpful if `Recorder` could include `addFrame` and `downloadBundle` methods so that I may keep these frames in separate bundles while maintaining a light footprint of using `canvas-recorder`.

✌️

**Comment by MathiasPaumgarten** [comment]
Finally had some time to get around to this. If you update to version `1.8.0` you get the methods mentioned above in the Recorder class. It is much cleaner this way anyway.

**Comment by hapticdata** [comment]
woo hoo! OSS FTW
